#!/bin/bash

if [[ $1 == "-h" ]] || [[ $# -lt 1 ]]; then
	echo usage $1
	echo "  -h: usage message"
	echo "  <device,device....>:  List of devices to check to see if they are mounted"
	exit 1
fi

mount_tmp=`mktemp /tmp/mount_temp.XXXXX`
mount | cut -d' ' -f1 > $mount_tmp
#
# Now lvms
#
if [[ -d /dev/mapper ]]; then
	pushd /dev/mapper > /dev/null
	for i in `ls | grep -v control`; do
		value=`lvdisplay --maps $i | grep "Physical volume" | cut -d'/' -f2-`
		echo /$value >> $mount_tmp
	done
	popd > /dev/null
fi
#
# Now check for mounted
#
for var in "$@"
do
	grep -qx $var $mount_tmp
	if [ $? -eq 0 ]; then
		rm $mount_tmp
		exit 1
	fi
done
rm $mount_tmp
exit 0

