#!/bin/bash
disks_passed=$1
disks=""

seper=""

grab_disks()
{
	if test -f "hw_config.yml"; then
		disks=`grep storage hw_config.yml | cut -d: -f 2 | sed "s/,/ /g"`
	else
		ALLSTG=$(mktemp /tmp/allstgdsk.XXXXX)
		USEDDSK=$(mktemp /tmp/useddsk.XXXXX)
		ALLDSK=$(mktemp /tmp/alldsk.XXXXX)
		MNTDDSK=$(mktemp /tmp/mntddsk.XXXXX)
		lsblk -l > ${ALLSTG}
		rootdisk=$(grep -e "part /$" -e boot$ ${ALLSTG} | awk '{print $1}')
	
		if [[ $rootdisk =~ nvme* ]]; then
			grep part ${ALLSTG}| grep -e / -e swap | awk '{print $1}' | sed s/p[[:digit:]]*$// | sort | uniq > $USEDDSK
		else
			grep -e disk -e part ${ALLSTG}| grep -e / -e swap | awk '{print $1}' | sed s/[[:digit:]]*$// | sort | uniq > $USEDDSK
		fi
		#
		# Now the mounted disks
		#
		for i in `df | grep /dev | cut -d' ' -f1 | grep /`
		do 
			echo ${i##*/} >> $USEDDSK
		done

		grep disk ${ALLSTG} | awk '{print $1}' | sort | uniq > ${ALLDSK}
		disks=`echo $(grep -F -x -v -f ${USEDDSK} ${ALLDSK})`
	fi
	echo "$disks"  | awk '{ for (i=NF; i > 1; i--) printf("%s ",$i); print $1; }' > disks
	disks=`cat disks`
}

retrieve_available_disks()
{
	#
	# We are going to use all the unmounted disks.
	#
	grab_disks
	for i in `cat disks`; do
		let "numb_disks=$numb_disks + 1"
		disks=${disks}${seper}/dev/${i}
		seper=" "
	done
}

if [[ $disks_passed == *"none"* ]]; then
	if [[ $sys_type == "local" ]]; then
		echo Unable to continue. non cloud systems require a disk to be designated.
		exit 1
	fi
fi

if [[ $disks_passed == "grab_disks" ]]; then
	retrieve_available_disks
else
	#
	# Use the list of disks passed in.
	#
	disk_list=`echo $disks_passed | sed 's/,/ /g'`
	for i in $disk_list; do
		let "numb_disks=$numb_disks + 1"
		disks=${disks}${seper}/dev/${i}
		seper=" "
	done
fi
#
# If no disks have been passed in, bail.  Note we do not check
# to make sure the disk exist.
#
if [ $numb_disks -eq 0 ]; then
	report_info "Need to have disks to do fio"
	exit 1
fi
echo  $disks:$numb_disks
