#!/bin/bash
#
# Copyright (C) 2022  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#


lvm_vol=""
lvm_grp=""
mount_pnt=""

usage()
{
	echo "Usage: $1"
	echo " --lvm_grp: name of the lvm group removing"
	echo " --lvm_vol: name of the lvm volume removing"
	echo " --mount_pnt: mount point of the lvm"
	exit 0
}


#
# Define options
#
ARGUMENT_LIST=(
	"lvm_vol"
        "lvm_grp"
        "mount_pnt"
)

NO_ARGUMENTS=(
        "usage"
)

# read arguments
opts=$(getopt \
    --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
    --longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
    --name "$(basename "$0")" \
    --options "h" \
    -- "$@"
)

if [ $? -ne 0 ]; then
        exit
fi
eval set --$opts

while [[ $# -gt 0 ]]; do
	case "$1" in
		--lvm_vol)
			lvm_vol=${2}
			shift 2
		;;
		--lvm_grp)
			lvm_grp=${2}
			shift 2
		;;
		--mount_pnt)
			mount_pnt=${2}
			shift 2
		;;
		--usage)
			usage $0
		;;
		-h)
			usage $0
		;;
		--)
			break;
		;;
		*)
			echo option not found $1
			usage $0
		;;
	esac
done

umount $mount_pnt
lvremove -f $lvm_vol/$lvm_grp
vgremove -f $lvm_vol
