#!/bin/bash
prefix="no_prefix_deisgnated"
user=""

usage()
{
	echo "Usage: $1"
	echo "  --prefix: prefix to attach to the results"
	echo "  --user: Name of the user.  If blank, will be the current user"
	exit 1
}


#
# Define options
#
ARGUMENT_LIST=(
	"hostname"
        "prefix"
	"user"
)

NO_ARGUMENTS=(
        "usage"
)

# read arguments
opts=$(getopt \
    --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
    --longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
    --name "$(basename "$0")" \
    --options "h" \
    -- "$@"
)

if [ $? -ne 0 ]; then
        exit
fi
eval set --$opts

while [[ $# -gt 0 ]]; do
	case "$1" in
		--hostname)
			fhost=$2
			shift 2
		;;
		--prefix)
			results_prefix=$2
			shift 2
		;;
		--user)
			user=$2
			shift 2
		;;
		--usage)
			usage $0
		;;
		-h)
			usage $0
		;;
		--)
			break;
		;;
		*)
			echo option not found $1
			usage $0
		;;
	esac
done
date_value=`date +"%D" | sed "s/\//_/g"`
full_hostname=${fhost}_${user}_${date_value}
export full_hostname

echo pbench-copy-results --user $user --prefix $results_prefix >> /tmp/debugging
pbench-copy-results --user $user --prefix $results_prefix
retVal=$?
while [ $retVal -gt 0 ]; do
	#
	# We failed, sleep a bit and then try again.
	echo pbench-copy-results failed, retrying $retval >> /tmp/debugging
	sleep 30
	pbench-copy-results --user $user --prefix $results_prefix
	retVal=$?
done

