#!/bin/bash
#
# Copyright (C) 2022  David Valin dvalin@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

prefix="no_prefix_designated"
user=""

usage()
{
	echo "Usage: $1"
	echo "  --prefix: prefix to attach to the results"
	echo "  --user: Name of the user.  If blank, will be the current user"
}


#
# Define options
#
ARGUMENT_LIST=(
	"copy"
	"hostname"
	"prefix"
	"user"
)

NO_ARGUMENTS=(
	"usage"
)

# read arguments
opts=$(getopt \
	--longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
	--longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
	--name "$(basename "$0")" \
	--options "h" \
	-- "$@"
)

copy=0

if [ $? -ne 0 ]; then
	exit 1
fi
eval set -- $opts

while [[ $# -gt 0 ]]; do
	#
	# Ansible is being stupind on azure
	#
	value=`echo $2 | sed "s/}//g"`
	case "$1" in
		--copy)
			copy=$value
			shift 2
		;;
		--hostname)
			fhost=$value
			shift 2
		;;
		--prefix)
			results_prefix=$value
			shift 2
		;;
		--user)
			user=$value
			shift 2
		;;
		--usage)
			usage $0
			exit 0
		;;
		-h)
			usage $0
			exit 0
		;;
		--)
			shift 1
			break
		;;
		*)
			echo option not found $1 >&2
			usage $0 >&2
			exit 1
		;;
	esac
done

controller=${fhost}_${user}
if [[ "$controller" == *"--"* ]]; then
	echo Error controller $controller contains "--"! >> /tmp/debugging
	exit 1
fi

if [[ "$user" == *"--"* ]]; then
	echo Error user $user contains "--"! >> /tmp/debugging
	exit 1
fi

if [[ "$results_prefix" == *"--"* ]]; then
	echo Error results_prefix $results_prefix contains "--"! >> /tmp/debugging
	exit 1
fi

#
# Because pbench does a hostname validation, and it will not allow "_"
#
controller_name=`echo ${controller} | sed "s/_/-/g"`

if [ $copy -eq 0 ]; then
	echo pbench-move-results --controller="\"${controller_name}\"" --user="\"${user}\"" --prefix="\"${results_prefix}\"" >> /tmp/debugging
	pbench-move-results --controller="${controller_name}" --user="${user}" --prefix="${results_prefix}"
else
	echo pbench-copy-results --controller="\"${controller_name}\"" --user="\"${user}\"" --prefix="\"${results_prefix}\"" >> /tmp/debugging
	pbench-copy-results --controller="${controller_name}" --user="${user}" --prefix="${results_prefix}"
fi
exit $?
