- name: RHEL # Human Readable name
  identifier: rhel # Identifier present in /etc/os-release, also the string that everything prints out
  uname_pattern: \.el[0-9]+ # Regex of uname pattern to identifiy the OS, this is also passed to the version pattern
  uname_version_pattern: "[0-9]+" # Regex to extract the version number from the captured uname pattern

- name: Ubuntu
  identifier: ubuntu 
  uname_pattern: Ubuntu
  # Ubuntu does not supply version information in uname, so by not supplying a version regex, this step is skipped

- name: Amazon Linux
  identifier: amzn
  uname_pattern: amzn2(023)?
  uname_version_pattern: 2(023)?

- name: Fedora
  identifier: fedora
  uname_pattern: \.fc[0-9]+\.
  uname_version_pattern: "[0-9]+"
